export const ACTIONS = {
    APPLY_FILTER: 'APPLY_FILTER',
    FETCH_DATA: 'FETCH_DATA',
    UPDATE_SEARCH: 'UPDATE_SEARCH',
    CLEAR_SEARCH: 'CLEAR_SEARCH',
    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER'
};
